### ISSUE TITLE
Publish latest version to NPM

### ISSUE THREAD

**Issue by JohnLouderback** [Richienb/vlc-static#2]
Can you please publish the latest version to NPM? I'm trying to use Audic, but it won't work without this being updated as it cannot download the VLC binaries.

**Comment by Richienb** [comment]
👍

The only reason why I haven't published a new version is that I'm not sure if the MacOS support actually works yet.

**Comment by Richienb** [comment]
Done! https://github.com/Richienb/vlc-static/releases/tag/v1.0.4
